# Generated by Django 5.1.7 on 2025-04-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_face_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citoyen'), ('admin', 'Administrateur')], default='citizen', max_length=20),
        ),
    ]
